### ISSUE TITLE
Yolo detector seg fault

### ISSUE THREAD

**Issue by mattslathrop** [OpenPTrack/open_ptrack_v2#22] opened 2018-06-14 16:59 UTC
When I run `roslaunch tracking yolo_detection_and_tracking_kinect.launch` I get the following error:

>[yolo_detector_node-5] process has died [pid 4974, exit code -11, cmd /home/[user]/workspace/ros/devel/lib/yolo_detector/open_ptrack_yolo_detector_node __name:=yolo_detector_node __log:=/home/[user]/.ros/log/6f81f0d0-6ff3-11e8-89b5-6805ca5a6bbb/yolo_detector_node-5.log].
log file: /home/[user]/.ros/log/6f81f0d0-6ff3-11e8-89b5-6805ca5a6bbb/yolo_detector_node-5*.log

(I have subbed my username with [user]
The log file mentioned in the error doesn't exist though. If I run the command `/home/[user]/workspace/ros/devel/lib/yolo_detector/open_ptrack_yolo_detector_node __name:=yolo_detector_node __log:=/home/[user]/.ros/log/6f81f0d0-6ff3-11e8-89b5-6805ca5a6bbb/yolo_detector_node-5.log` I get 

> Loading weights from /home/misappsci/workspace/ros/src/open_ptrack/yolo_detector/darknet_opt/yolo.weights...exitDone!
/home/misappsci/workspace/ros/src/open_ptrack/yolo_detector/data
Segmentation fault (core dumped)

Still no log file is created that I can find.

**Comment by SimeonOA** [comment] 2018-06-20 21:18
Hi, 

A fix for this is available in the the branch [iss21](https://github.com/OpenPTrack/open_ptrack_v2/tree/iss21). Please use that branch.

Thank you

Simeon

**Comment by youpicontini** [comment] 2018-11-05 17:15
Hi, 
lauching the `roslaunch tracking yolo_detection_and_tracking_kinect.launch` or `roslaunch detection detection_node_kinect01.launch enable_pose:=true enable_object:=false enable_people_tracking:=true
` (with yolo configured in the camera_network.yalm) commands get me the error:

> ERROR: cannot launch node of type [yolo_detector/open_ptrack_yolo_detector_node]: can't locate node [open_ptrack_yolo_detector_node] in package [yolo_detector]

I wanted to checkout the iss21 branch, but it is not available anymore. 

Any similar issue?

**Comment by SimeonOA** [comment] 2018-11-05 17:52
Hi,

The command to run is `roslaunch tracking tracking_node.launch` or` roslaunch tracking tracking_node.launch enable_pose:=false enable_object:=false enable_people_tracking:=true` on the Master. The above publishes calibration data, performs tracking, and opens Rviz in order to track results.

Next you run on every sensor including the Master:  `roslaunch detection detection_node_<sensor>.launch` or `roslaunch detection detection_node_<sensor>.launch enable_pose:=false enable_object:=false enable_people_tracking:=true`. 

Note that you can change the flags to true or false depending on what module you are interested in. Running the commands without the flags activates all three modules.

The iss21 branch has been merged with Master. 

Please let us know if you need anything else.

Simeon

**Comment by Harsharma2308** [comment] 2019-01-07 04:56
I guess you mean `roslaunch detection detection_<sensor>.launch`. But none of these launch files launch the kinect2_bridge.
The problem is that the _yolo_detector_node_ whenever it receives an image from the kinect, it just shows segmentation fault and the node dies.
How do I resolve this ?

**Comment by SimeonOA** [comment] 2019-01-07 05:42
Hi,

Did you carry out [calibration](https://github.com/OpenPTrack/open_ptrack_v2/wiki/Calibration)?

The detection_node_<sensor_id>.launch files are created during calibration. 

Also when running  the command `roslaunch tracking tracking_node.launch` or `roslaunch tracking tracking_node.launch enable_pose:=false enable_object:=false enable_people_tracking:=true` should be run on only the Master while `roslaunch detection detection_node_<sensor>.launch` or `roslaunch detection detection_node_<sensor>.launch enable_pose:=false enable_object:=false enable_people_tracking:=true` should be run on every sensor including the Master. 

Thanks

Simeon

**Comment by bsubbaraman** [comment] 2019-11-06 23:12
Closing as this issue has been resolved.

**Closed by bsubbaraman** 2019-11-06 23:12 UTC
